-- 0019_notifications: in-app notification inbox + per-user email preferences
-- (Phase 5). Notifications are a personal cross-org inbox: each row targets one
-- recipient (user_id) and is generated by an actor's action on an issue.

CREATE TABLE notifications (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,  -- recipient
    actor_id        UUID REFERENCES users(id) ON DELETE SET NULL,           -- who triggered it
    type            TEXT NOT NULL CHECK (type IN ('mention', 'comment', 'assigned', 'activity')),
    issue_id        UUID REFERENCES issues(id) ON DELETE CASCADE,
    issue_key       TEXT NOT NULL DEFAULT '',  -- denormalized for display
    title           TEXT NOT NULL,
    body            TEXT NOT NULL DEFAULT '',
    read_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX notifications_user_idx ON notifications (user_id, created_at DESC);
CREATE INDEX notifications_user_unread_idx ON notifications (user_id) WHERE read_at IS NULL;

CREATE TABLE notification_preferences (
    user_id           UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    email_mentions    BOOLEAN NOT NULL DEFAULT true,
    email_comments    BOOLEAN NOT NULL DEFAULT true,
    email_assignments BOOLEAN NOT NULL DEFAULT true,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
